
spring:
  security:
    oauth2:
      client:
        provider:
          facebook:
            user-name-attribute: email
        registration:
          facebook:
            clientId: 883154592551348
            clientSecret: dbd1b2b9e82d876d7ee7742d7f67fde0
            scope:
              - email
              - public_profile
  flyway:
    baseline-on-migrate: true
  datasource:
    url: "jdbc:postgresql://localhost:5432/postgres"
    username: postgres
    password: password
    initialization-mode: always
