paypal:
  clientId: AZ7ahR39k9cCddEn-hBid9cy3eP-N_vjlH1-jJHN2ZnS6zzCeyfU8Xnr1uMLm99Q1vRKGastczR-Z-Q6
  clientSecret: EAxctIlTF5OVAO9Xc92YZr8MG10TANzQnBEJWwH492eQ-74XNyj3Nx-q2kLf-_vibJGGsXMwJTMqc7Ey

spring:
  security:
    oauth2:
      client:
        provider:
          facebook:
            user-name-attribute: email
        registration:
          facebook:
            clientId: 883154592551348
            clientSecret: dbd1b2b9e82d876d7ee7742d7f67fde0
            scope:
              - email
              - public_profile
  flyway:
    baseline-on-migrate: true
  datasource:
    url: "jdbc:postgresql://localhost:5432/postgres"
    username: postgres
    password: password
    initialization-mode: always
